### PR TITLE
Update thumbor, thumbor-aws and envtpl packages

### PR DESCRIPTION
**Pull request by altendorfme**
thumbor to 7.5.2
thumbor-aws to 0.6.0
envtpl to 0.7.2

### CODE REVIEW

**Comment by mvhirsch** [comment]
Thank you very much! Did you check added/removed ENV variables, too?

**Comment by mvhirsch** [comment]
Closes #13

**Comment by altendorfme** [comment]
I didn't check the variables, I opened an issue on the official thumbor to help with some documentation. I will validate and update this PR again.

**Comment by altendorfme** [comment]
Compares:

`thumbor.conf `
https://raw.githubusercontent.com/thumbor/thumbor/3e35fc024e895313d4b8c1da29286b96859ae122/thumbor/thumbor.conf 
https://raw.githubusercontent.com/mvhirsch/thumbor-docker/master/7/slim/thumbor.conf.tpl

Is totally same!

`Dockerfile`
https://github.com/thumbor/thumbor/blob/master/docker/Dockerfile
https://github.com/mvhirsch/thumbor-docker/blob/master/7/slim/Dockerfile

Has 4 differences, in official Thumbor has apt packages: `libjpeg-dev`, `libwebp-dev`, `zlib1g-dev`, `libcairo2-dev`

**Comment by mvhirsch** [comment]
Nice! Will release the new version, soon. Thx!

**Comment by mvhirsch** [comment]
Released & Docker images built. Thank you very much @altendorfme !

**Pull request merged**
